# Generated by Django 4.2.28 on 2026-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_delete_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
